# Generated by Django 3.2.3 on 2021-05-26 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoveOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('move_out_date', models.DateField(verbose_name='Move-out date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.address', verbose_name='address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
