# Generated by Django 3.2.3 on 2021-05-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
    ]
